### ISSUE TITLE
no

### ISSUE THREAD

**Issue by zz1616611** [maximbaz/browser-fingerprint-protector#1]
System time does not match The system time set by your computer does not match your IP time zone

https://whoer.net
https://browserleaks.com/ip

**Comment by max-baz** [comment]
Hey, thanks for the suggestion!

I wanted to keep this extension minimal and zero-config. For faking time zone, you would need to configure somewhere what time zone you want your browser to report, and it is annoying and error prone because you would need to change this setting very frequently.

Unless you have ideas how to implement this in an automated way that doesn't require user to manually choose what time zone they want, I don't think this is worth implementing.

Closing for now, but let me know if you have some ideas and if I like I'll implement them.
