### ISSUE TITLE
Does not hide browser version.

### ISSUE THREAD

**Issue by ZdrytchX** [maximbaz/browser-fingerprint-protector#3]
I'd like to hide the browser version information from a website but the feature isnt present in the current version of the plugin

**Comment by max-baz** [comment]
Hi, what do you have in mind exactly, hiding it completely or pretending that you use e.g. Firefox? The former would defeat the purpose of trying to protect against fingerprinting (because you will be the only one in the world whose browser version cannot be detected), the latter could cause some troubles if e.g. some websites would send you Firefox specific hacks that are not meant for non Firefox browsers. 

The best approach against browser fingerprinting is to have your information not hidden, but on the contrary look exactly like the rest of the people.
