### ISSUE TITLE
fingerprintjs v3

### ISSUE THREAD

**Issue by russian-developer** [maximbaz/browser-fingerprint-protector#4]
Hello,

I've found your job as a good one.

But your extension doesn't work with https://github.com/fingerprintjs/fingerprintjs

Could you please check it out?

**Comment by max-baz** [comment]
Hello 👋 

Before we go into the discussion let me just first clarify, the purpose of the extension is:
- **not** to block extensions like fingerprintjs
- **not** to get a different fingerprint ID every time you refresh a page

Because both of these actions actually almost uniquely identify you (if fingerprintjs is able to calculate ID of everyone _except_ you, this fact makes you stand out from the crowd; same is if everyone else's ID persists while they move between different pages of the same website but your ID changes every time, this again makes you stand out from the crowd).

The purpose of this extension is to try to make you blend in the crowd, to try to reduce the confidence level of extensions like fingerprintjs when they assign ID to you. So for example, if a majority of users browse internet using Windows 10 and you alone in your neighborhood use FreeBSD, by this marker alone fingerprintjs can be quite confident that it's still you even if you change browser, language, time, etc, you are still the only one who uses FreeBSD in your area.

I found that OS / User Agent, a list of installed languages, mimeTypes and plugins is something that has very high change of being unique to almost every single person, so this extension either hides them completely (like some browsers do anyway) or uses most common values.

The ideal solution is to make tools like fingerprintjs so much unconfident that while our ID is persistent, if we were to change some information that we leak (say change IP address, country, time or browser), then fingerprintjs is instantly fooled. But I'm not sure this ideal goal is achievable, to be honest 😞 

Does this clarify some things for you? Do you have any ideas what else we could try to spoof, pretend we use the most common values? Please feel free to share your thoughts 🙂

**Comment by russian-developer** [comment]
Thank you for the explanation. It was my mistake, because, I thought that your tool was created for user anonymization. I was wrong. Thanks.
