### ISSUE TITLE
https://pixelscan.net/

### ISSUE THREAD

**Issue by aliafshany** [maximbaz/browser-fingerprint-protector#5]
hi there

when the extension is on, https://pixelscan.net/ can detect something is wrong and we are masking the fingerprint. when it's off, everything is ok

could you please take a look at that?

**Comment by max-baz** [comment]
Hello!

Thanks for the ping, this is interesting! Interestingly enough for me the website always shows that something is wrong, even in clean chromium in incognito 🤔 

In any case, I'm afraid I don't know what we can do, their code is obfuscated and I'm not sure what we could be doing to improve...

**Comment by aliafshany** [comment]
well for me it is working fine as long as the extension is turned off, which you can see at this picture
<img width="824" alt="Screen Shot 2021-02-21 at 21 51 47" src="https://user-images.githubusercontent.com/40741745/108634493-0bef5b00-747a-11eb-80a4-021a10af00b7.png">
the  only thing os red is that i'm using a proxy and nothing i can do about it :)

best

**Comment by max-baz** [comment]
Curious... But still I'm afraid I don't know what we can do, and I don't even have a way to test some ideas as they always flag me.

If you feel like experimenting and you find some interesting ideas, please share, maybe we can merge some improvements 🙂

**Comment by aliafshany** [comment]
of course dear maximbaz, i will let you know if i found a way.
oh and something else, could add profiles like Chameleon (an extension for firefox) so we can change profile from windows 10 to anything we want? and of course adding a timezone changer would be great
best regards

**Comment by max-baz** [comment]
I wanted a way to have this extension zero config, in part to make sure that it's hard to accidentally misconfigure to suddenly become a "unique" user on the internet (who is therefore fingerprinted with 100% success rate), in part because I mainly use this extension in a QtWebEngine-based browser which doesn't expose any UI / popup / settings for extension configuration. 

Windows 10 is therefore picked simply because it's the most common OS, so it reduces the fingerprint the most. Timezone I was thinking about, but didn't think of any good way to do it automatically (see also #1)...

**Comment by max-baz** [comment]
I'll close the issue as there isn't anything I can do for pixelscan, but as already mentioned if you do discover something, please share 🙂
