### ISSUE TITLE
Does not work with CloudFlare

### ISSUE THREAD

**Issue by Serega007RU** [maximbaz/browser-fingerprint-protector#6]
With this extension, it is impossible to pass the CloudFlare check, it gives an error
```
Uncaught TypeError: navigator.plugins.item is not a function
```

**Comment by max-baz** [comment]
Interesting, thanks for letting me know, do you know of any quick way I could reproduce?

**Comment by Serega007RU** [comment]
Well, you can try to reproduce it here https://captcha.website/
![image](https://user-images.githubusercontent.com/64780091/151146816-f32a4381-5fc7-49ef-b9be-190bd5e979bc.png)

**Comment by Serega007RU** [comment]
Here it looks like the CloudFlare code where this error occurs.
![image](https://user-images.githubusercontent.com/64780091/151151636-d4372264-9e4b-4cdb-9b27-3946b57d880b.png)

I'm not sure, but most likely because of this, CloudFlare does not pass verification

**Comment by max-baz** [comment]
You are right, the reason for the issue is that we pretend that our browser has no plugins, so we return an empty error when someone tries to call `navigator.plugins`:

https://github.com/maximbaz/browser-fingerprint-protector/blob/4ff506ce62f62ea9f9552fc1b207e748d3fb4e0f/src/inject.js#L29-L31

And for some reason calling `.item(0)` on empty array gives an exception.... Very strange!

**Comment by max-baz** [comment]
Maybe we can experiment with returning something else, I think returning `[]` didn't work for me, but maybe there is a more clever way to do it...

**Comment by Serega007RU** [comment]
Well, probably it can be done like this
```JS
 window.navigator.__defineGetter__("plugins", function() { 
   return {
      length: 0,
      item: (index) => {return null}
   }; 
 });
```

**Comment by max-baz** [comment]
I couldn't find any better way than what you proposed in your (deleted) comment, so I just went with it. Thanks for reporting, and for suggesting the fix 😉

**Comment by Serega007RU** [comment]
I didn't just delete my message because it still didn't solve my problem. And so, I vote here https://www.xtremetop100.com/in.php?site=1132314593 On this site after you click "Vote for ..." the CloudFlare check will begin. (To trigger this check, you must clear the cf_clearance cookies) This check does not pass with your extension, either the CloudFlare check will take a very long time to pass or you will be thrown back. There are no errors in the console. I am not 100% sure that the problem is with CloudFlare and not with the site xtremetop100.com

I do not know how to solve this problem, but if you comment out these lines of code
https://github.com/maximbaz/browser-fingerprint-protector/blob/255d29ae061ebb3d51121ceb9dbea10a09ee7d89/src/inject.js#L14-L19
and these
https://github.com/maximbaz/browser-fingerprint-protector/blob/255d29ae061ebb3d51121ceb9dbea10a09ee7d89/src/inject.js#L34-L41
then the cloudflare check will pass.

**Comment by max-baz** [comment]
Very strange! I confirm... I also don't see any errors, I'm not really sure what's going on and what to fix...

 I think your initial suggestion was definitely good to include, because at least captcha.website functions now. I also just found out about https://wicg.github.io/ua-client-hints, apparently there are more headers now that leak platform info...

I don't know what to do about xtremetop100, if you ever figure out or have any ideas, let me know... This war against fingerprinting never stops 😞 😅

**Comment by fenglengshun** [comment]
I had this issue as well - was trying to open fanfiction.net , but I was just kept on a loop of cloudflare anti-DDOS protection.

Perhaps a temporary disable or selective disabling feature could be a useful workaround? I just disable the extensions when dealing with cloudflare, as it is.
